version: "3.9"
services:
    frontend:
        container_name: frontend
        image: fapp-frontend:latest
        build: 
            dockerfile: ./frontend/Dockerfile
            context: .
        ports: 
            - "4200:4200"

    backend:
        container_name: backend
        image: fapp-backend:latest
        build: 
            dockerfile: ./backend/Dockerfile
            context: .
        ports: 
            - "8000:8000"
