version: "3.9"
services:
  frontend:
    container_name: frontend
    hostname: frontend
    image: fang-frontend:latest
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
        USERNAME: ${DOCKER_USERNAME}
    user: ${DOCKER_UID}:${DOCKER_GID}

  backend:
    container_name: backend
    hostname: backend
    image: fang-backend:latest
    build:
      dockerfile: ./backend/Dockerfile
      context: .
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
        USERNAME: ${DOCKER_USERNAME}
    user: ${DOCKER_UID}:${DOCKER_GID}
    ports:
      - 8000:8000
    environment:
      DB_URI: ${DB_URI}
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    ports:
      - 8080:8080
    user: ${DOCKER_UID}:${DOCKER_GID}

volumes:
  postgres_data:
